apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app: orders
spec:
  replicas: {{ .Values.orders.replicaCount }}
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: {{ .Values.orders.image }}
          ports:
            - containerPort: {{ .Values.orders.port }}
          env:
            - name: PODINFO_UI_MESSAGE
              value: pulse-orders
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.orders.port }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.orders.port }}
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  selector:
    app: orders
  ports:
    - port: 80
      targetPort: {{ .Values.orders.port }}
