apiVersion: platform.aegis.dev/v1
kind: Tenant
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: tenant-sample
spec:
  # TODO(user): Add fields here
